#!/usr/bin/env python3
"""Generate the human-readable skill index from installed repository packages."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


GENERATED_HEADER = (
    "<!-- Generated by scripts/generate-skill-index.py. Do not edit manually. -->"
)


class IndexError(Exception):
    """Raised when a package or grouping cannot produce a trustworthy index."""


@dataclass(frozen=True)
class Skill:
    name: str
    description: str
    portability: str


def parse_scalar(value: str) -> str:
    value = value.strip()
    if value.startswith('"'):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as exc:
            raise IndexError(f"invalid quoted frontmatter value: {value}") from exc
        if not isinstance(parsed, str):
            raise IndexError(f"frontmatter value must be a string: {value}")
        return parsed
    if value.startswith("'"):
        if len(value) < 2 or not value.endswith("'"):
            raise IndexError(f"invalid quoted frontmatter value: {value}")
        return value[1:-1].replace("''", "'")
    return value


def read_skill(skill_dir: Path) -> Skill:
    skill_file = skill_dir / "SKILL.md"
    try:
        lines = skill_file.read_text(encoding="utf-8-sig").splitlines()
    except OSError as exc:
        raise IndexError(f"cannot read {skill_file}: {exc}") from exc
    if not lines or lines[0].strip() != "---":
        raise IndexError(f"{skill_file} must start with YAML frontmatter")
    try:
        closing = next(i for i, line in enumerate(lines[1:], 1) if line.strip() == "---")
    except StopIteration as exc:
        raise IndexError(f"{skill_file} has no closing frontmatter delimiter") from exc

    values: dict[str, str] = {}
    portability = "not-declared"
    for line in lines[1:closing]:
        match = re.match(r"^([A-Za-z][A-Za-z0-9_-]*):\s*(.+?)\s*$", line)
        if match and match.group(1) in {"name", "description"}:
            values[match.group(1)] = parse_scalar(match.group(2))
        portability_match = re.match(r"^\s+portability:\s*(.+?)\s*$", line)
        if portability_match:
            portability = parse_scalar(portability_match.group(1))

    for field in ("name", "description"):
        if not values.get(field):
            raise IndexError(f"{skill_file} is missing a usable {field}")
    if values["name"] != skill_dir.name:
        raise IndexError(
            f"{skill_file} declares {values['name']!r}, expected {skill_dir.name!r}"
        )
    return Skill(values["name"], values["description"], portability)


def markdown_cell(value: str) -> str:
    return " ".join(value.split()).replace("|", "\\|")


def render(root: Path) -> str:
    skills_root = root / "skills"
    grouping_file = root / "skills.sh.json"
    if not skills_root.is_dir():
        raise IndexError(f"missing skills directory: {skills_root}")
    try:
        grouping = json.loads(grouping_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise IndexError(f"cannot read {grouping_file}: {exc}") from exc

    skills = {
        path.name: read_skill(path)
        for path in sorted(skills_root.iterdir(), key=lambda item: item.name)
        if path.is_dir() and (path / "SKILL.md").is_file()
    }
    if not skills:
        raise IndexError("no skill packages found")

    seen: set[str] = set()
    sections: list[tuple[str, str, list[Skill]]] = []
    for group in grouping.get("groupings", []):
        title = group.get("title")
        description = group.get("description", "")
        names = group.get("skills")
        if not isinstance(title, str) or not isinstance(description, str) or not isinstance(names, list):
            raise IndexError("each skills.sh.json grouping needs title, description, and skills")
        members: list[Skill] = []
        for name in names:
            if name not in skills:
                raise IndexError(f"skills.sh.json references missing skill: {name}")
            if name in seen:
                raise IndexError(f"skill appears in more than one grouping: {name}")
            seen.add(name)
            members.append(skills[name])
        if members:
            sections.append((title, description, members))

    ungrouped = [skills[name] for name in sorted(skills.keys() - seen)]
    if ungrouped:
        sections.append(("Ungrouped", "Skill packages not assigned in `skills.sh.json`.", ungrouped))

    lines = [
        GENERATED_HEADER,
        "",
        "# Skill index",
        "",
        "Chỉ mục này được sinh từ frontmatter của `skills/*/SKILL.md` và nhóm trong",
        "`skills.sh.json`. Nội dung runtime nằm ở từng `SKILL.md`; package README",
        "chỉ cung cấp hướng dẫn và provenance bổ sung.",
        "",
        "Không sửa file này trực tiếp. Sau khi thêm hoặc đổi skill, chạy:",
        "",
        "```bash",
        "python scripts/generate-skill-index.py",
        "bash scripts/validate-skills.sh .",
        "```",
    ]
    for title, description, members in sections:
        lines.extend(["", f"## {title}", ""])
        if description:
            lines.extend([description, ""])
        lines.extend(
            [
                "| Skill | Trigger / outcome | Portability | Runtime contract |",
                "|---|---|---|---|",
            ]
        )
        for skill in members:
            package_readme = root / "skills" / skill.name / "README.md"
            links = f"[SKILL.md](../../skills/{skill.name}/SKILL.md)"
            if package_readme.is_file():
                links += f" · [README](../../skills/{skill.name}/README.md)"
            lines.append(
                f"| `{skill.name}` | {markdown_cell(skill.description)} | "
                f"`{markdown_cell(skill.portability)}` | {links} |"
            )
    lines.extend(
        [
            "",
            "## Pickup rule",
            "",
            "1. Chọn candidate theo mô tả được lấy trực tiếp từ `SKILL.md`.",
            "2. Đọc toàn bộ `SKILL.md` của candidate trước khi thực thi.",
            "3. Chỉ tải reference, template hoặc script mà router của skill yêu cầu.",
            "4. `not-declared` nghĩa package chưa công bố portability; không tự suy luận rằng",
            "   package đó standalone.",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--check", action="store_true", help="fail when the generated index is stale")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    output = root / "docs" / "skills" / "README.md"
    try:
        expected = render(root)
        if args.check:
            actual = output.read_text(encoding="utf-8") if output.is_file() else ""
            if actual != expected:
                print(
                    "Skill index is stale. Run: python scripts/generate-skill-index.py",
                    file=sys.stderr,
                )
                return 1
            print(f"Skill index is current: {output}")
            return 0
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(expected, encoding="utf-8", newline="\n")
        print(output)
        return 0
    except IndexError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
